server:
  port: 8082

spring:
  application:
    name: config-start
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
    active: native

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8081/eureka/


