server:
  port: 8083

spring:
  application:
    name: bus-start
  rabbitmq:
    host: 172.24.20.218
    port: 5672
    username: admin
    password: admin123

management:
  security:
    enabled: false

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8081/eureka/

test:
  age: 1111111
  name: 1111111111111111



