server:
  port: 8083

spring:
  application:
    name: consumer-test
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8081/eureka/


